In [79]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [78]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn import metrics
import numpy as np

In [80]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

In [81]:
Titanic = sns.load_dataset('titanic')

In [30]:
Titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

# Data Wrangling 

In [31]:
Titanic['sex1'] = np.where(Titanic['sex'] == "male", 1, np.where(Titanic['sex'] == "female", 2, 3))

In [32]:
Titanic.embarked.value_counts()

S    644
C    168
Q     77
Name: embarked, dtype: int64

In [33]:
Titanic.deck.value_counts()

C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: deck, dtype: int64

In [34]:
Titanic.embark_town.value_counts()

Southampton    644
Cherbourg      168
Queenstown      77
Name: embark_town, dtype: int64

In [35]:
Titanic['embarked1'] = np.where(Titanic['embarked'] =="S",1, np.where(Titanic['embarked'] == "C",2, np.where(Titanic['embarked'] == "Q",3,4)))

In [36]:
Titanic['class1'] = np.where(Titanic['class'] == "First", 1, np.where(Titanic['class'] == "Second", 2, np.where(Titanic['class'] == "Third", 3,4 )))

In [37]:
Titanic['who1'] = np.where(Titanic['who'] =="female",1, np.where(Titanic['who'] == "male",2,3))

In [38]:
Titanic['adult_male1'] = np.where(Titanic['adult_male'] =="true",1, np.where(Titanic['adult_male'] == "false",2,3)) 

In [39]:
Titanic['deck1'] = np.where(Titanic['deck'] =="C",1, np.where(Titanic['deck'] == "B",2, np.where(Titanic['deck'] == "D",3, np.where(Titanic['deck'] =="E",4, np.where(Titanic['deck'] == "A",5, np.where(Titanic['deck'] == "F",6, np.where(Titanic['deck'] == "G",7,8 )))))))

In [63]:
Titanic = Titanic.drop('embark_town',axis=1)

In [64]:
Titanic['alive1'] = np.where(Titanic['alive'] =="yes",1, np.where(Titanic['alive'] == "no",2, 3))

In [65]:
Titanic['alone1'] = np.where(Titanic['alive'] =="False",1, np.where(Titanic['alive'] == "True",2, 3))

In [66]:
Titanic

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1           1       1  female  38.0      1      0  71.2833        C  First   
3           1       1  female  35.0      1      0  53.1000        S  First   
6           0       1    male  54.0      0      0  51.8625        S  First   
10          1       3  female   4.0      1      1  16.7000        S  Third   
11          1       1  female  58.0      0      0  26.5500        S  First   
..        ...     ...     ...   ...    ...    ...      ...      ...    ...   
871         1       1  female  47.0      1      1  52.5542        S  First   
872         0       1    male  33.0      0      0   5.0000        S  First   
879         1       1  female  56.0      0      1  83.1583        C  First   
887         1       1  female  19.0      0      0  30.0000        S  First   
889         1       1    male  26.0      0      0  30.0000        C  First   

       who  ...  alive  alone sex1  embarked1  class1  who1  adult_male1  \
1    woman  ...    yes  False    2          2       1     3            3   
3    woman  ...    yes  False    2          1       1     3            3   
6      man  ...     no   True    1          1       1     3            3   
10   child  ...    yes  False    2          1       3     3            3   
11   woman  ...    yes   True    2          1       1     3            3   
..     ...  ...    ...    ...  ...        ...     ...   ...          ...   
871  woman  ...    yes  False    2          1       1     3            3   
872    man  ...     no   True    1          1       1     3            3   
879  woman  ...    yes  False    2          2       1     3            3   
887  woman  ...    yes   True    2          1       1     3            3   
889    man  ...    yes   True    1          2       1     3            3   

     deck1  alive1  alone1  
1        1       1       3  
3        1       1       3  
6        4       2       3  
10       7       1       3  
11       1       1       3  
..     ...     ...     ...  
871      3       1       3  
872      2       2       3  
879      1       1       3  
887      2       1       3  
889      1       1       3  

[182 rows x 22 columns]

In [67]:
Titanic1.info() 

<class 'pandas.core.frame.DataFrame'>
Int64Index: 182 entries, 1 to 889
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     182 non-null    int64   
 1   pclass       182 non-null    int64   
 2   sex          182 non-null    object  
 3   age          182 non-null    float64 
 4   sibsp        182 non-null    int64   
 5   parch        182 non-null    int64   
 6   fare         182 non-null    float64 
 7   embarked     182 non-null    object  
 8   class        182 non-null    category
 9   who          182 non-null    object  
 10  adult_male   182 non-null    bool    
 11  deck         182 non-null    category
 12  alive        182 non-null    object  
 13  alone        182 non-null    bool    
 14  sex1         182 non-null    int32   
 15  embarked1    182 non-null    int32   
 16  class1       182 non-null    int32   
 17  who1         182 non-null    int32   
 18  adult_male1  182 non-null    i

**Drop missing and infinite values**

In [68]:
Titanic.dropna(inplace=True)

# Define x and Y

In [69]:
x = Titanic [['age','sibsp','parch','fare','sex1','embarked1','class1','who1','adult_male','deck1','alone1']]

In [70]:
y = Titanic [['alive1']]

# Train test 

In [71]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

# Create Tree

In [72]:
decisionTree = DecisionTreeClassifier()
decisionTree.fit(x_train, y_train)

DecisionTreeClassifier()

# Assess the Model

In [73]:
treePredictions = decisionTree.predict(x_test)

In [74]:
treePredictions

array([1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1])

In [75]:
print(confusion_matrix(y_test, treePredictions))

[[35  7]
 [ 6  7]]


In [76]:

print(classification_report(y_test, treePredictions))

              precision    recall  f1-score   support

           1       0.85      0.83      0.84        42
           2       0.50      0.54      0.52        13

    accuracy                           0.76        55
   macro avg       0.68      0.69      0.68        55
weighted avg       0.77      0.76      0.77        55



# Random Forest

In [82]:
forest = RandomForestClassifier(n_estimators=500, random_state=76)
forest.fit(x_train, y_train)

C:\Users\Summe\AppData\Local\Temp\ipykernel_9000\2130838707.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  forest.fit(x_train, y_train)


RandomForestClassifier(n_estimators=500, random_state=76)

In [83]:
forestPredictions = forest.predict(x_test)
print(confusion_matrix(y_test, forestPredictions))
print(classification_report(y_test, forestPredictions))

[[35  7]
 [ 7  6]]
              precision    recall  f1-score   support

           1       0.83      0.83      0.83        42
           2       0.46      0.46      0.46        13

    accuracy                           0.75        55
   macro avg       0.65      0.65      0.65        55
weighted avg       0.75      0.75      0.75        55



**This model shows 75% accuracy**